// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0n_4olgKX-NOUuYTmHZtnT7uyD8dYTF0',
    appId: '1:605157754958:web:5860c264a3a125c8569b1f',
    messagingSenderId: '605157754958',
    projectId: 'ui-project-81fe5',
    authDomain: 'ui-project-81fe5.firebaseapp.com',
    databaseURL: 'https://ui-project-81fe5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ui-project-81fe5.firebasestorage.app',
    measurementId: 'G-P3CW516MBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgl0ayV6OkJdxyKeXmVQ51H7jpb3DSek4',
    appId: '1:605157754958:android:7dd4ad2c429ed9ef569b1f',
    messagingSenderId: '605157754958',
    projectId: 'ui-project-81fe5',
    databaseURL: 'https://ui-project-81fe5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ui-project-81fe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ2A5nOf2Nik2qgCsxWqsa__8YUckXzZk',
    appId: '1:605157754958:ios:af496650682574e4569b1f',
    messagingSenderId: '605157754958',
    projectId: 'ui-project-81fe5',
    databaseURL: 'https://ui-project-81fe5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ui-project-81fe5.firebasestorage.app',
    iosBundleId: 'com.example.uiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ2A5nOf2Nik2qgCsxWqsa__8YUckXzZk',
    appId: '1:605157754958:ios:af496650682574e4569b1f',
    messagingSenderId: '605157754958',
    projectId: 'ui-project-81fe5',
    databaseURL: 'https://ui-project-81fe5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ui-project-81fe5.firebasestorage.app',
    iosBundleId: 'com.example.uiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0n_4olgKX-NOUuYTmHZtnT7uyD8dYTF0',
    appId: '1:605157754958:web:db4e47470e880aaf569b1f',
    messagingSenderId: '605157754958',
    projectId: 'ui-project-81fe5',
    authDomain: 'ui-project-81fe5.firebaseapp.com',
    databaseURL: 'https://ui-project-81fe5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ui-project-81fe5.firebasestorage.app',
    measurementId: 'G-99654FHZTF',
  );
}
